compatibility_date = "2023-05-09"
main = "src/index.ts"
name = "english-line-bot"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_id = "f43f9b85-c94e-4065-beea-1d48a0c0a778" 
database_name = "english-line-bot-db"
